FROM node

# Build Args
ARG AUTH_ID
ARG AUTH_TOKEN

# Run time environment variables
ENV AUTH_ID=${AUTH_ID} AUTH_TOKEN=${AUTH_TOKEN}

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8081

CMD [ "npm", "start" ]