FROM node:12

# Set the default port of the backend
ENV PORT=8081
EXPOSE 8081

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# If you are building your code for production
# RUN npm ci --only=production
RUN npm install

# Bundle app source
COPY . .

CMD [ "node", "index.js" ]
